# Generated by Django 4.1.5 on 2023-01-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Категория статьи"),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("description", models.TextField(verbose_name="Описание категории")),
            ],
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории",},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название статьи"),
                ),
                ("slug", models.SlugField(max_length=100, null=True, unique=True)),
                (
                    "anons",
                    models.CharField(blank=True, max_length=1000, verbose_name="Анонс"),
                ),
                (
                    "full_text",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Статья"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="article/",
                        verbose_name="Изображение",
                    ),
                ),
                ("draft", models.BooleanField(default=False, verbose_name="Черновик")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shpargalka.categoryarticle",
                        verbose_name="Категория статьи",
                    ),
                ),
            ],
            options={"verbose_name": "Статья", "verbose_name_plural": "Статьи",},
        ),
    ]
