# Generated by Django 4.1.5 on 2023-01-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0002_alter_categoryarticle_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="anons",
            field=models.TextField(blank=True, max_length=1000, verbose_name="Анонс"),
        ),
    ]
