# Generated by Django 4.1.5 on 2023-01-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0003_alter_article_anons"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="category", new_name="category_article",
        ),
        migrations.RenameField(
            model_name="article", old_name="image", new_name="image_article",
        ),
        migrations.RenameField(
            model_name="article", old_name="slug", new_name="slug_article",
        ),
        migrations.RenameField(
            model_name="categoryarticle",
            old_name="description",
            new_name="description_cat",
        ),
        migrations.RenameField(
            model_name="categoryarticle", old_name="name", new_name="name_cat",
        ),
        migrations.RenameField(
            model_name="categoryarticle", old_name="slug", new_name="slug_cat",
        ),
    ]
