# Generated by Django 4.1.5 on 2023-01-06 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0004_rename_category_article_category_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="full_text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
