# Generated by Django 4.1.5 on 2023-01-06 15:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0005_alter_article_full_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="anons", field=ckeditor.fields.RichTextField(),
        ),
    ]
