# Generated by Django 4.1.5 on 2023-01-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0006_alter_article_anons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image_article",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="article_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
