# Generated by Django 4.1.5 on 2023-01-14 12:14

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0008_categorypost_alter_article_anons_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTreeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_cat",
                    models.CharField(max_length=150, verbose_name="Категория статьи"),
                ),
                ("slug_cat", models.SlugField(max_length=160, unique=True)),
                (
                    "description_cat",
                    models.TextField(blank=True, verbose_name="Описание категории"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shpargalka.categorytreearticle",
                        verbose_name="РОДИТЕЛЬСКИЙ класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория (Tree)",
                "verbose_name_plural": "Категории (Tree)",
                "db_table": "category_tree",
                "ordering": ("tree_id", "level"),
            },
        ),
    ]
