# Generated by Django 4.1.5 on 2023-01-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0009_categorytreearticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="number_post",
            field=models.IntegerField(blank=True, null=True, verbose_name="Нумерация"),
        ),
    ]
