# Generated by Django 4.1.5 on 2023-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0010_article_number_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="number_post",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Нумерация"
            ),
        ),
    ]
