# Generated by Django 4.1.5 on 2023-01-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0012_alter_article_number_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="number_post",
            field=models.PositiveIntegerField(
                blank=True, max_length=2, null=True, verbose_name="Нумерация"
            ),
        ),
    ]
