# Generated by Django 4.1.5 on 2023-01-16 16:55

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0013_alter_article_number_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название статьи"),
                ),
                (
                    "slug_article",
                    models.SlugField(max_length=100, null=True, unique=True),
                ),
                (
                    "number_post",
                    models.PositiveIntegerField(
                        blank=True, max_length=2, null=True, verbose_name="Нумерация"
                    ),
                ),
                ("anons", models.TextField(blank=True, verbose_name="Анонс")),
                ("full_text", models.TextField(blank=True, verbose_name="Статья")),
                (
                    "image_article",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="article_images/",
                        verbose_name="Изображение",
                    ),
                ),
                ("draft", models.BooleanField(default=False, verbose_name="Черновик")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category_article",
                    mptt.fields.TreeForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cat_tree",
                        to="shpargalka.categorytreearticle",
                        verbose_name="Категория статьи tree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья tree",
                "verbose_name_plural": "Статьи tree",
                "ordering": ("category_article", "number_post"),
            },
        ),
        migrations.DeleteModel(name="CategoryPost",),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("category_article", "number_post"),
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
