# Generated by Django 4.1.5 on 2023-02-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shpargalka", "0015_alter_articletree_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="number_post",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Нумерация"
            ),
        ),
        migrations.AlterField(
            model_name="articletree",
            name="number_post",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Нумерация"
            ),
        ),
    ]
